apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-pipeline
spec:
  serviceAccountName: pipeline
  triggers:
  - name: test-trigger
    interceptors:
    - cel:
        filter: "body.ref == 'refs/head/master'"
    bindings:
    - name: github-push
      kind: ClusterTriggerBinding
    template:
      name: test-pipeline-trigger